# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: staged_backup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13staged_backup.proto\x12\x0cStagedBackup\"\xb4\x02\n\rPathInfoProto\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x37\n\tpath_type\x18\x02 \x01(\x0e\x32$.StagedBackup.PathInfoProto.PathType\x12\x0c\n\x04mode\x18\x03 \x01(\x04\x12\r\n\x05mtime\x18\x04 \x01(\x03\x12\x0c\n\x04size\x18\x05 \x01(\x04\x12\x0b\n\x03uid\x18\x06 \x01(\r\x12\x0b\n\x03gid\x18\x07 \x01(\r\x12\x11\n\tlink_dest\x18\x08 \x01(\t\x12\x0e\n\x06sha256\x18\t \x01(\x0c\x12\x12\n\nxattr_hash\x18\n \x01(\x0c\x12\x12\n\nxattr_keys\x18\x0b \x03(\t\x12 \n\x18google_drive_remote_file\x18\x0c \x01(\x08\"*\n\x08PathType\x12\x07\n\x03\x44IR\x10\x00\x12\x08\n\x04\x46ILE\x10\x01\x12\x0b\n\x07SYMLINK\x10\x02\"@\n\rManifestProto\x12/\n\npath_infos\x18\x01 \x03(\x0b\x32\x1b.StagedBackup.PathInfoProtob\x06proto3')



_PATHINFOPROTO = DESCRIPTOR.message_types_by_name['PathInfoProto']
_MANIFESTPROTO = DESCRIPTOR.message_types_by_name['ManifestProto']
_PATHINFOPROTO_PATHTYPE = _PATHINFOPROTO.enum_types_by_name['PathType']
PathInfoProto = _reflection.GeneratedProtocolMessageType('PathInfoProto', (_message.Message,), {
  'DESCRIPTOR' : _PATHINFOPROTO,
  '__module__' : 'staged_backup_pb2'
  # @@protoc_insertion_point(class_scope:StagedBackup.PathInfoProto)
  })
_sym_db.RegisterMessage(PathInfoProto)

ManifestProto = _reflection.GeneratedProtocolMessageType('ManifestProto', (_message.Message,), {
  'DESCRIPTOR' : _MANIFESTPROTO,
  '__module__' : 'staged_backup_pb2'
  # @@protoc_insertion_point(class_scope:StagedBackup.ManifestProto)
  })
_sym_db.RegisterMessage(ManifestProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PATHINFOPROTO._serialized_start=38
  _PATHINFOPROTO._serialized_end=346
  _PATHINFOPROTO_PATHTYPE._serialized_start=304
  _PATHINFOPROTO_PATHTYPE._serialized_end=346
  _MANIFESTPROTO._serialized_start=348
  _MANIFESTPROTO._serialized_end=412
# @@protoc_insertion_point(module_scope)
